version: "3"

services:
  php:
    image: ambientum/php:7.3-nginx
    ports:
      - 80:8080
    volumes:
      - .:/var/www/app

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "veganation"
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql:/var/lib/mysql
