version: "3.7"
services:
  app:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./docker/php
      dockerfile: Dockerfile
    image: veganation
    container_name: veganation-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - veganation

  db:
    image: mysql:5.7
    container_name: veganation-db
    restart: unless-stopped
    ports:
      - 33061:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - dbdata:/var/lib/mysql/
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - veganation

  nginx:
    image: nginx:alpine
    container_name: veganation-nginx
    restart: unless-stopped
    ports:
      - 8082:80
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - veganation

networks:
  veganation:
    driver: bridge

volumes:
  dbdata:
    driver: local